server:
  port: 8080
spring:
  datasource:
    mysql:
      name: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&useSSL=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&allowMultiQueries=true
      hikari:
        maximum-pool-size: 12
        connection-timeout: 60000
        minimum-idle: 10
        idle-timeout: 500000
        max-lifetime: 540000
        connection-test-query: SELECT 1
    postgres:
      name: postgre-sql
      driver-class-name: org.postgresql.Driver
      username: omoptest
      password: 123456
      url: jdbc:postgresql://127.0.0.1:5432/device_embedding
      hikari:
        maximum-pool-size: 12
        connection-timeout: 60000
        minimum-idle: 10
        idle-timeout: 500000
        max-lifetime: 540000
        connection-test-query: SELECT 1
